repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: check-ast
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        args: [--fail-under=80, --quiet]
        exclude: ^node_modules/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        args: [--install-types, --non-interactive]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-beta.0
    hooks:
    -   id: eslint
        additional_dependencies:
        - eslint@3.12.2
        - eslint-config-google@0.7.1
        - eslint-config-prettier@1.7.0
        - eslint-plugin-vue@8.0.3
